/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yhon.dam.proyectodamnavidad;

import com.yhon.dam.proyectodamnavidad.controller.LoginControlador;
import com.yhon.dam.proyectodamnavidad.controller.LoginControlador.LoginResult;
import com.yhon.dam.proyectodamnavidad.modelo.Recompensa;
import com.yhon.dam.proyectodamnavidad.modelo.Usuario;
import com.yhon.dam.proyectodamnavidad.util.HibernateUtil;
import com.yhon.dam.proyectodamnavidad.util.I18n;
import com.yhon.dam.proyectodamnavidad.util.I18nAware;
import com.yhon.dam.proyectodamnavidad.vista.RecuperarPasswordVista;
import javax.swing.JOptionPane;
import com.yhon.dam.proyectodamnavidad.vista.RegistroVista;
import com.yhon.dam.proyectodamnavidad.vista.TareasVista;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.hibernate.Session;

/**
 * Ventana principal de la aplicación.
 * <p>
 * Esta clase representa la pantalla de inicio de sesión del sistema de gestión
 * de tareas familiares. Desde aquí se permite:
 * </p>
 * <ul>
 * <li>Iniciar sesión de usuarios</li>
 * <li>Acceder al registro de nuevos usuarios</li>
 * <li>Recuperar contraseña</li>
 * <li>Cambiar el idioma de la aplicación</li>
 * </ul>
 *
 * Implementa {@link com.yhon.dam.proyectodamnavidad.util.I18nAware} para
 * soportar internacionalización dinámica.
 *
 * @author yhon
 */
public class MainFrame extends javax.swing.JFrame implements I18nAware {

    /**
     * Fuente original del label de recuperación de contraseña, utilizada para
     * restaurar el estilo tras el efecto hover.
     */
    private Font label4NormalFont;
    /**
     * Logger de la clase MainFrame.
     */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Crea la ventana principal de inicio de sesión.
     * <p>
     * Inicializa los componentes gráficos, establece el idioma por defecto,
     * carga datos iniciales y centra la ventana.
     * </p>
     */
    public MainFrame() {
        initComponents();
        I18n.setLanguage("es"); // idioma por defecto
        label4NormalFont = recuperarPassword.getFont();
        inicializarDatos();
        getRootPane().setDefaultButton(jButton1);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Inicializa los datos básicos de la aplicación.
     * <p>
     * Comprueba si existen recompensas en la base de datos y, en caso
     * contrario, inserta un conjunto inicial de recompensas. Este método se
     * ejecuta al iniciar la aplicación.
     * </p>
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        recuperarPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        espaniol = new javax.swing.JMenuItem();
        ingles = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("GESTOR DE TAREAS");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        recuperarPassword.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        recuperarPassword.setText("He olvidado mi contraseña");
        recuperarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recuperarPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                recuperarPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                recuperarPasswordFocusLost(evt);
            }
        });
        recuperarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recuperarPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recuperarPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recuperarPasswordMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagenDeLogin.png"))); // NOI18N

        jMenu4.setText("Sesion");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Nuevo Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Idioma");

        espaniol.setText("Español");
        espaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaniolActionPerformed(evt);
            }
        });
        jMenu1.add(espaniol);

        ingles.setText("Ingles");
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        jMenu1.add(ingles);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem5.setText("Controles");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1)
                    .addComponent(recuperarPassword)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recuperarPassword)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarDatos() {
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {

            session.beginTransaction();

            Long count;
            try {
                count = session.createQuery(
                        "SELECT COUNT(r) FROM Recompensa r", Long.class
                ).uniqueResult();
            } catch (Exception e) {
                count = 0L; // tabla aún no existe (H2 nuevo)
            }

            if (count == 0) {

                session.persist(new Recompensa("Elegir la película", 500));
                session.persist(new Recompensa("1 hora de consola", 200));
                session.persist(new Recompensa("2 horas de consola", 400));
                session.persist(new Recompensa("Elegir juego de mesa", 300));
                session.persist(new Recompensa("Tarde de juegos en familia", 500));
                session.persist(new Recompensa("Ir al cine", 500));
                session.persist(new Recompensa("Maratón de series", 1000));
                session.persist(new Recompensa("Elegir la música del día", 200));
                session.persist(new Recompensa("Elegir qué ver en la TV", 300));
                session.persist(new Recompensa("Postre especial", 200));
                session.persist(new Recompensa("Elegir la cena", 400));
                session.persist(new Recompensa("Cenar fuera", 1000));
                session.persist(new Recompensa("Pedir comida a domicilio", 1000));
                session.persist(new Recompensa("Helado o dulce especial", 200));
                session.persist(new Recompensa("Desayuno especial", 300));
                session.persist(new Recompensa("Noche de pizza", 600));
                session.persist(new Recompensa("Día libre sin tareas", 1000));
                session.persist(new Recompensa("Mañana libre", 500));
                session.persist(new Recompensa("Dormir una hora más", 300));
                session.persist(new Recompensa("Tarde libre", 400));
                session.persist(new Recompensa("Fin de semana sin tareas", 10000));
                session.persist(new Recompensa("Obtener un regalo pequeño", 1000));
                session.persist(new Recompensa("Obtener un regalo", 1500));
                session.persist(new Recompensa("Regalo especial", 10000));
                session.persist(new Recompensa("Vale sorpresa", 800));
            }

            session.getTransaction().commit();
        }
    }

    /**
     * Maneja el evento de inicio de sesión.
     * <p>
     * Valida las credenciales introducidas y, según el resultado, permite el
     * acceso a la aplicación o muestra un mensaje de error.
     * </p>
     *
     * @param evt evento de acción generado al pulsar el botón
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = jTextField1.getText();
        String password = new String(jPasswordField1.getPassword());

        LoginControlador controller = new LoginControlador();
        LoginResult result = controller.login(username, password);

        switch (result) {
            case OK:
                Usuario usuario = controller.getUsuarioLogueado();

                TareasVista vista = new TareasVista(usuario);
                vista.setLocationRelativeTo(this);
                vista.setVisible(true);

                this.dispose(); // cerrar login
                break;

            case USER_NOT_FOUND:
                Object[] options = {I18n.t("common.ok")};

                JOptionPane.showOptionDialog(
                        this,
                        I18n.t("login.userNotFound"),
                        I18n.t("login.error"),
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.WARNING_MESSAGE,
                        null,
                        options,
                        options[0]
                );
                break;

            case WRONG_PASSWORD:
                Object[] options2 = {I18n.t("common.ok")};

                JOptionPane.showOptionDialog(
                        this,
                        I18n.t("login.wrongPassword"),
                        I18n.t("login.error"),
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.ERROR_MESSAGE,
                        null,
                        options2,
                        options2[0]
                );
                break;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        RegistroVista registro = new RegistroVista();
        registro.setLocationRelativeTo(this); // centrado respecto al login
        registro.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        RegistroVista registro = new RegistroVista();
        registro.setLocationRelativeTo(this);
        registro.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void recuperarPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_recuperarPasswordFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_recuperarPasswordFocusGained

    private void recuperarPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_recuperarPasswordFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_recuperarPasswordFocusLost

    private void recuperarPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuperarPasswordMouseEntered
        /**
         * Aplica un subrayado al texto cuando el ratón entra en el label.
         *
         * @param evt evento de ratón
         */
        Map<TextAttribute, Object> attributes
                = new HashMap<>(label4NormalFont.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);

        recuperarPassword.setFont(label4NormalFont.deriveFont(attributes));
    }//GEN-LAST:event_recuperarPasswordMouseEntered

    private void recuperarPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuperarPasswordMouseExited
        /**
         * Restaura el estilo original del texto al salir el ratón.
         *
         * @param evt evento de ratón
         */
        recuperarPassword.setFont(label4NormalFont);
    }//GEN-LAST:event_recuperarPasswordMouseExited

    private void recuperarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuperarPasswordMouseClicked
        /**
         * Abre la ventana de recuperación de contraseña.
         *
         * @param evt evento de ratón generado al hacer clic
         */
        RecuperarPasswordVista v = new RecuperarPasswordVista();
        v.setLocationRelativeTo(this);
        v.setVisible(true);

    }//GEN-LAST:event_recuperarPasswordMouseClicked

    private void espaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaniolActionPerformed
        /**
         * Cambia el idioma de la aplicación a español.
         *
         * @param evt evento de acción
         */
        I18n.setLanguage("es");
        aplicarIdioma();

    }//GEN-LAST:event_espaniolActionPerformed

    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        /**
         * Cambia el idioma de la aplicación a inglés.
         *
         * @param evt evento de acción
         */
        I18n.setLanguage("en");
        aplicarIdioma();

    }//GEN-LAST:event_inglesActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        /**
         * Muestra la ventana de ayuda con los controles de la aplicación.
         *
         * @param evt evento de acción
         */

        Object[] options = {I18n.t("common.ok")};

        JOptionPane.showOptionDialog(
                this,
                I18n.t("help.content"),
                I18n.t("help.title"),
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]
        );
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem espaniol;
    private javax.swing.JMenuItem ingles;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel recuperarPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void aplicarIdioma() {
        /**
         * Aplica el idioma seleccionado a todos los textos visibles de la
         * ventana.
         * <p>
         * Este método se ejecuta tras un cambio de idioma y actualiza
         * etiquetas, botones y menús.
         * </p>
         */
        setTitle(I18n.t("tasks.title"));
        jLabel1.setText(I18n.t("login.title"));
        jLabel2.setText(I18n.t("login.user"));
        jLabel3.setText(I18n.t("login.password"));
        jButton1.setText(I18n.t("login.send"));

        jMenuItem2.setText(I18n.t("menu.logout"));
        jMenu1.setText(I18n.t("menu.lenguage"));
        recuperarPassword.setText(I18n.t("login.forgot"));

        jMenu4.setText(I18n.t("menu.sesion"));
        jMenuItem2.setText(I18n.t("menu.newuser"));

        espaniol.setText(I18n.t("menu.spanish"));
        ingles.setText(I18n.t("menu.english"));
        jMenu2.setText(I18n.t("menu.help"));
        jMenuItem5.setText(I18n.t("menu.controls"));
    }

}
