/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yhon.dam.proyectodamnavidad.vista;

import com.yhon.dam.proyectodamnavidad.dao.UsuarioDAO;
import com.yhon.dam.proyectodamnavidad.modelo.Usuario;
import com.yhon.dam.proyectodamnavidad.util.I18n;
import com.yhon.dam.proyectodamnavidad.util.I18nAware;
import com.yhon.dam.proyectodamnavidad.util.PasswordUtil;
import javax.swing.JOptionPane;

/**
 * Ventana para el cambio de contraseña del usuario autenticado.
 * <p>
 * Permite al usuario introducir su contraseña actual y establecer
 * una nueva contraseña de forma segura.
 * </p>
 *
 * La vista soporta internacionalización dinámica mediante
 * la interfaz {@link I18nAware}.
 *
 * @author yhon
 */
public class CambiarContrasenaVista extends javax.swing.JFrame implements I18nAware {
    
     /** Logger de la clase */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CambiarContrasenaVista.class.getName());
    
    /** Carácter original usado para ocultar la contraseña */
    private char echoCharOriginal;

     /** Usuario actualmente autenticado */
    private Usuario usuarioLogueado;

      /**
     * Crea la ventana de cambio de contraseña.
     *
     * @param usuarioLogueado usuario que ha iniciado sesión
     */
    public CambiarContrasenaVista(Usuario usuarioLogueado) {
        initComponents();
        this.usuarioLogueado = usuarioLogueado;
        echoCharOriginal = jPasswordField1.getEchoChar();
        setLocationRelativeTo(null);
        aplicarIdioma();
        
        /**
     * Inicializa los componentes gráficos.
     * <p>
     * ⚠ Método generado automáticamente por NetBeans.
     * No debe modificarse manualmente.
     * </p>
     */
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        verpassword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        verpassword1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        verpassword.setText("ver");
        verpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verpasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                verpasswordMouseReleased(evt);
            }
        });

        jLabel3.setText("Nueva Contraseña");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("CREAR NUEVA CONTRASEÑA");

        jButton1.setText("Cambiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        verpassword1.setText("ver");
        verpassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verpassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verpassword1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                verpassword1MouseReleased(evt);
            }
        });

        jLabel4.setText("Antigua Contraseña");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nuevapassword.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verpassword))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verpassword1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)))
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verpassword1))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verpassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Muestra temporalmente la nueva contraseña mientras se mantiene pulsado el ratón.
     */
    private void verpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verpasswordMousePressed
        // TODO add your handling code here:
        jPasswordField1.setEchoChar((char) 0); // mostrar contraseña
    }//GEN-LAST:event_verpasswordMousePressed
    
    /**
     * Vuelve a ocultar la nueva contraseña al soltar el ratón.
     */
    private void verpasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verpasswordMouseReleased
        // TODO add your handling code here:
        jPasswordField1.setEchoChar(echoCharOriginal); // ocultar
    }//GEN-LAST:event_verpasswordMouseReleased
    
     /**
     * Muestra temporalmente la contraseña antigua.
     */
    private void verpassword1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verpassword1MousePressed
        jPasswordField2.setEchoChar((char) 0);
    }//GEN-LAST:event_verpassword1MousePressed
    
     /**
     * Oculta de nuevo la contraseña antigua.
     */
    private void verpassword1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verpassword1MouseReleased
        // TODO add your handling code here:
        jPasswordField2.setEchoChar(echoCharOriginal);
    }//GEN-LAST:event_verpassword1MouseReleased
    
     /**
     * Gestiona el proceso de cambio de contraseña.
     * <p>
     * Valida los campos, comprueba la contraseña antigua,
     * genera el nuevo hash y lo guarda en la base de datos.
     * </p>
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        char[] oldPass = jPasswordField2.getPassword();
        char[] newPass = jPasswordField1.getPassword();

        Object[] okOption = {I18n.t("common.ok")};

        if (oldPass.length == 0 || newPass.length == 0) {

            JOptionPane.showOptionDialog(
                    this,
                    I18n.t("password.empty"),
                    I18n.t("common.warning"),
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    okOption,
                    okOption[0]
            );
            return;
        }

        // 🔐 Comprobar contraseña antigua
        if (!PasswordUtil.checkPassword(
                new String(oldPass),
                usuarioLogueado.getPasswordHash()
        )) {

            JOptionPane.showOptionDialog(
                    this,
                    I18n.t("password.oldIncorrect"),
                    I18n.t("common.error"),
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.ERROR_MESSAGE,
                    null,
                    okOption,
                    okOption[0]
            );
            return;
        }

        // 🔒 Generar hash nueva contraseña
        String newHash = PasswordUtil.hashPassword(new String(newPass));

        // 💾 Guardar en BD
        UsuarioDAO.actualizarPassword(usuarioLogueado, newHash);

        // 🔄 Actualizar objeto en memoria
        usuarioLogueado.setPasswordHash(newHash);

        JOptionPane.showOptionDialog(
                this,
                I18n.t("password.changed"),
                I18n.t("common.success"),
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                okOption,
                okOption[0]
        );

        // 🧹 Limpiar arrays por seguridad
        java.util.Arrays.fill(oldPass, '\0');
        java.util.Arrays.fill(newPass, '\0');

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Cierra la ventana sin realizar cambios.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel verpassword;
    private javax.swing.JLabel verpassword1;
    // End of variables declaration//GEN-END:variables
    
    
    /**
     * Aplica los textos traducidos según el idioma actual.
     */
    @Override
    public void aplicarIdioma() {
        setTitle(I18n.t("password.change.title"));

        jLabel1.setText(I18n.t("password.change.header"));
        jLabel4.setText(I18n.t("password.old"));
        jLabel3.setText(I18n.t("password.new"));

        jButton1.setText(I18n.t("password.change.button"));

        verpassword.setText(I18n.t("common.show"));
        verpassword1.setText(I18n.t("common.show"));
    }
}
