/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yhon.dam.proyectodamnavidad.vista;

import com.toedter.calendar.JDateChooser;
import com.yhon.dam.proyectodamnavidad.MainFrame;
import com.yhon.dam.proyectodamnavidad.dao.TareaDAO;
import com.yhon.dam.proyectodamnavidad.modelo.Tarea;
import com.yhon.dam.proyectodamnavidad.modelo.Usuario;
import com.yhon.dam.proyectodamnavidad.util.I18n;
import com.yhon.dam.proyectodamnavidad.util.I18nAware;
import java.awt.event.KeyEvent;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 * Ventana para la creación de nuevas tareas.
 * <p>
 * Permite al usuario crear una tarea indicando nombre, responsable,
 * fechas, descripción y puntos de recompensa.
 * </p>
 *
 * Soporta internacionalización dinámica mediante {@link I18nAware}.
 *
 * @author yhon
 */
public class CrearTareaVista extends javax.swing.JFrame implements I18nAware {
    /** Usuario que crea la tarea */
    private Usuario usuarioLogueado;
    /** Vista padre desde la que se abre esta ventana */
    private TareasVista vistaPadre;
    /** Logger de la clase */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearTareaVista.class.getName());

  
    /**
     * Crea la ventana de creación de tareas.
     *
     * @param usuarioLogueado usuario autenticado
     * @param vistaPadre vista principal de tareas
     */
    public CrearTareaVista(Usuario usuarioLogueado, TareasVista vistaPadre) {
        initComponents();
        this.usuarioLogueado = usuarioLogueado;
        this.vistaPadre = vistaPadre;
        aplicarIdioma();
        cargarUsuarios();
        SpinnerNumberModel model = new SpinnerNumberModel(
                0, // inicial
                0, // mínimo
                1000, // máximo
                10 // incremento
        );
        spPuntos.setModel(model);
    }
    
     /**
     * Carga los usuarios disponibles como responsables de la tarea.
     */
    private void cargarUsuarios() {
        List<Usuario> usuarios = TareaDAO.listarUsuarios();
        for (Usuario u : usuarios) {
            comboResponsable.addItem(u);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /**
     * Inicializa los componentes gráficos.
     * <p>
     * ⚠ Método generado automáticamente por NetBeans.
     * No debe modificarse manualmente.
     * </p>
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboResponsable = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dateInicio = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        dateFin = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblPuntos = new javax.swing.JLabel();
        spPuntos = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        cerrarSesion = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        espaniol = new javax.swing.JMenuItem();
        ingles = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CREAR TAREA");

        jLabel2.setText("Nombre de Tarea");

        jLabel3.setText("Responsable");

        jLabel4.setText("Fecha Inicio");

        jLabel5.setText("Fecha Limite");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel6.setText("Descripcion");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblPuntos.setText("Puntos");

        jMenu4.setText("Sesion");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        jMenu4.add(cerrarSesion);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Idioma");

        espaniol.setText("Español");
        espaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaniolActionPerformed(evt);
            }
        });
        jMenu1.add(espaniol);

        ingles.setText("Ingles");
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        jMenu1.add(ingles);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem5.setText("Controles");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPuntos)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(comboResponsable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(dateInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(dateFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(spPuntos))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lblPuntos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
     /**
     * Guarda la nueva tarea tras validar los datos introducidos.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int puntos = (int) spPuntos.getValue();

        String nombre = txtNombre.getText().trim();
        String descripcion = txtDescripcion.getText();
        Usuario responsable = (Usuario) comboResponsable.getSelectedItem();
        Date inicio = dateInicio.getDate();
        Date fin = dateFin.getDate();

        if (nombre.isEmpty() || responsable == null || inicio == null || fin == null) {
            JOptionPane.showMessageDialog(this,
                    I18n.t("task.create.required"),
                    I18n.t("common.error"),
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Tarea tarea = new Tarea(
                nombre,
                descripcion,
                usuarioLogueado,
                responsable,
                inicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),
                fin.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()
        );

        // 👇 AQUÍ se asignan los puntos (CORRECTO)
        tarea.setPuntosRecompensa(puntos);

        Object[] okOption = {I18n.t("common.ok")};

        if (TareaDAO.guardar(tarea)) {

            JOptionPane.showOptionDialog(
                    this,
                    I18n.t("task.create.success"),
                    I18n.t("common.success"),
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    okOption,
                    okOption[0]
            );

            vistaPadre.cargarTareas(); // refrescar tabla
            this.dispose(); // cerrar ventana

        } else {

            JOptionPane.showOptionDialog(
                    this,
                    I18n.t("task.create.error"),
                    I18n.t("common.error"),
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.ERROR_MESSAGE,
                    null,
                    okOption,
                    okOption[0]
            );
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Cambia el idioma a español.
     */
    private void espaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaniolActionPerformed
        // TODO add your handling code here:
        I18n.setLanguage("es");
        aplicarIdioma();
    }//GEN-LAST:event_espaniolActionPerformed
    
    /**
     * Cambia el idioma a inglés.
     */
    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        // TODO add your handling code here:
        I18n.setLanguage("en");
        aplicarIdioma();
    }//GEN-LAST:event_inglesActionPerformed
    
    /**
     * Muestra la ventana de ayuda.
     */
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Object[] options = {I18n.t("common.ok")};

        JOptionPane.showOptionDialog(
                this,
                I18n.t("help.content"),
                I18n.t("help.title"),
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]
        );

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
     /**
     * Cierra la sesión actual y vuelve a la pantalla de login.
     */
    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed

        // Botones traducidos
        Object[] options = {
            I18n.t("option.no"),
            I18n.t("option.yes")
        };

        int confirm = JOptionPane.showOptionDialog(
                this,
                I18n.t("menu.logout") + "?",
                I18n.t("menu.sesion"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
        );

        if (confirm != 1) { // 1 = Sí
            return;
        }

        this.dispose(); // Cierra la ventana actual

        MainFrame login = new MainFrame();
        login.setLocationRelativeTo(null); // Centrar
        login.setVisible(true);

    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        RegistroVista registro = new RegistroVista();
        registro.setLocationRelativeTo(this); // centrado respecto al login
        registro.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed
    
      /**
     * Cancela la creación de la tarea y cierra la ventana.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JComboBox<Usuario> comboResponsable;
    private com.toedter.calendar.JDateChooser dateFin;
    private com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JMenuItem espaniol;
    private javax.swing.JMenuItem ingles;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JSpinner spPuntos;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    
     /**
     * Aplica los textos traducidos según el idioma actual.
     */
    @Override
    public void aplicarIdioma() {
        jLabel1.setText(I18n.t("task.create.title"));
        jLabel2.setText(I18n.t("task.create.name"));
        jLabel3.setText(I18n.t("task.create.responsible"));
        jLabel4.setText(I18n.t("task.create.start"));
        jLabel5.setText(I18n.t("task.create.end"));
        jLabel6.setText(I18n.t("task.create.description"));
        lblPuntos.setText(I18n.t("task.create.points"));

        jButton1.setText(I18n.t("common.save"));
        jButton2.setText(I18n.t("common.cancel"));

        setTitle(I18n.t("task.create.window"));

        jMenu1.setText(I18n.t("menu.lenguage"));
        jMenu4.setText(I18n.t("menu.sesion"));

        cerrarSesion.setText(I18n.t("menu.logout"));
        espaniol.setText(I18n.t("menu.spanish"));
        ingles.setText(I18n.t("menu.english"));
        jMenu2.setText(I18n.t("menu.help"));
        jMenuItem5.setText(I18n.t("menu.controls"));
    }
}
