/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yhon.dam.proyectodamnavidad.vista;

import com.yhon.dam.proyectodamnavidad.MainFrame;
import com.yhon.dam.proyectodamnavidad.dao.RecompensaDAO;
import com.yhon.dam.proyectodamnavidad.dao.TareaDAO;
import com.yhon.dam.proyectodamnavidad.modelo.Recompensa;
import com.yhon.dam.proyectodamnavidad.modelo.Usuario;
import com.yhon.dam.proyectodamnavidad.util.I18n;
import com.yhon.dam.proyectodamnavidad.util.I18nAware;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana de canjeo de recompensas.
 * <p>
 * Muestra un listado de recompensas disponibles y permite al usuario
 * canjearlas si dispone de suficientes puntos.
 * </p>
 *
 * La vista soporta internacionalización dinámica mediante
 * {@link I18nAware}.
 *
 * @author yhon
 */
public class RecompensaVista extends javax.swing.JFrame implements I18nAware {
    /** Logger de la clase */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecompensaVista.class.getName());
    
    /** Usuario actualmente autenticado */
    private Usuario usuarioLogueado;
    
    /** Vista padre desde la que se abre esta ventana */
    private TareasVista vistaPadre;
    
    /** Modelo de la tabla de recompensas */
    private DefaultTableModel modeloTabla;

  /**
     * Crea la ventana de recompensas.
     *
     * @param usuarioLogueado usuario autenticado
     * @param vistaPadre vista principal de tareas
     */
    public RecompensaVista(Usuario usuarioLogueado, TareasVista vistaPadre) {
        initComponents();
        this.usuarioLogueado = usuarioLogueado;
        this.vistaPadre = vistaPadre;

        inicializarTabla();
        cargarRecompensas();
        configurarListenerTabla();
        aplicarIdioma();
        btnCanjear.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRecompensas = new javax.swing.JTable();
        btnCanjear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        cerrarSesion = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        espaniol = new javax.swing.JMenuItem();
        ingles = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaRecompensas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "OBJ", "Recompensa", "Coste (pts)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaRecompensas);

        btnCanjear.setText("Canjear");
        btnCanjear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanjearActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/familiaTrabajando.png"))); // NOI18N

        jMenu4.setText("Sesion");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        jMenu4.add(cerrarSesion);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Idioma");

        espaniol.setText("Español");
        espaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaniolActionPerformed(evt);
            }
        });
        jMenu1.add(espaniol);

        ingles.setText("Ingles");
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        jMenu1.add(ingles);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem5.setText("Controles");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnCanjear, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCanjear)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Gestiona el canjeo de una recompensa seleccionada.
     * <p>
     * Comprueba la selección, confirma la acción y valida
     * si el usuario dispone de puntos suficientes.
     * </p>
     */
    private void btnCanjearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanjearActionPerformed
        int fila = tablaRecompensas.getSelectedRow();

        // 🔹 Opciones traducidas
        Object[] okOption = {I18n.t("common.ok")};
        Object[] yesNoOptions = {
            I18n.t("option.no"),
            I18n.t("option.yes")
        };

        // No hay selección
        if (fila == -1) {
            JOptionPane.showOptionDialog(
                    this,
                    I18n.t("reward.select"),
                    I18n.t("common.warning"),
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    okOption,
                    okOption[0]
            );
            return;
        }

        Recompensa r = (Recompensa) modeloTabla.getValueAt(fila, 0);

        // Texto de confirmación (CORRECTO)
        String mensajeConfirmacion = String.format(
                I18n.t("reward.confirm"),
                r.getNombre(),
                r.getCostePuntos()
        );

        int confirm = JOptionPane.showOptionDialog(
                this,
                mensajeConfirmacion,
                I18n.t("reward.confirm.title"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                yesNoOptions,
                yesNoOptions[0]
        );

        if (confirm != 1) { // 1 = YES
            return;
        }

        // 3️⃣ Intentar canjear
        boolean ok = TareaDAO.canjearRecompensa(usuarioLogueado, r);

        if (ok) {

            JOptionPane.showOptionDialog(
                    this,
                    I18n.t("reward.success"),
                    I18n.t("common.success"),
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    okOption,
                    okOption[0]
            );

            vistaPadre.refrescarUsuario();
            dispose();

        } else {

            JOptionPane.showOptionDialog(
                    this,
                    I18n.t("reward.notEnoughPoints"),
                    I18n.t("common.error"),
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.ERROR_MESSAGE,
                    null,
                    okOption,
                    okOption[0]
            );
        }
    }//GEN-LAST:event_btnCanjearActionPerformed
    
     /**
     * Cambia el idioma a español.
     */
    private void espaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaniolActionPerformed
        // TODO add your handling code here:
        I18n.setLanguage("es");
        aplicarIdioma();
    }//GEN-LAST:event_espaniolActionPerformed
     /**
     * Cambia el idioma a inglés.
     */
    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        // TODO add your handling code here:
        I18n.setLanguage("en");
        aplicarIdioma();
    }//GEN-LAST:event_inglesActionPerformed

    
    /**
     * Cierra la sesión y vuelve a la pantalla de login.
     */
    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed

        // Botones traducidos
        Object[] options = {
            I18n.t("option.no"),
            I18n.t("option.yes")
        };

        int confirm = JOptionPane.showOptionDialog(
                this,
                I18n.t("menu.logout") + "?",
                I18n.t("menu.sesion"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
        );

        if (confirm != 1) { // 1 = Sí
            return;
        }

        this.dispose(); // Cierra la ventana actual

        MainFrame login = new MainFrame();
        login.setLocationRelativeTo(null); // Centrar
        login.setVisible(true);

    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        RegistroVista registro = new RegistroVista();
        registro.setLocationRelativeTo(this); // centrado respecto al login
        registro.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed
    
    /**
     * Muestra la ventana de ayuda.
     */
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Object[] options = {I18n.t("common.ok")};

        JOptionPane.showOptionDialog(
                this,
                I18n.t("help.content"),
                I18n.t("help.title"),
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]
        );
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
       /**
     * Cierra la ventana sin realizar acciones.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
     /**
     * Inicializa el modelo de la tabla y oculta la columna de objetos.
     */
    private void inicializarTabla() {
        modeloTabla = (DefaultTableModel) tablaRecompensas.getModel();

        // Ocultar columna OBJ
        tablaRecompensas.getColumnModel().getColumn(0).setMinWidth(0);
        tablaRecompensas.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaRecompensas.getColumnModel().getColumn(0).setWidth(0);
    }

     /**
     * Carga las recompensas desde la base de datos.
     */
    private void cargarRecompensas() {
        modeloTabla.setRowCount(0);

        for (Recompensa r : RecompensaDAO.listar()) {
            // Traducir el nombre de la recompensa antes de agregarlo a la tabla
            String nombreTraducido = I18n.getRewardTranslation(r.getNombre());

            modeloTabla.addRow(new Object[]{
                r, // Objeto completo
                nombreTraducido, // Nombre traducido
                r.getCostePuntos() // Coste en puntos
            });
        }
    }
    
     /**
     * Configura el listener de selección de la tabla
     * para habilitar o deshabilitar el botón de canjeo.
     */
    private void configurarListenerTabla() {
        tablaRecompensas.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting()) {
                return;
            }

            int fila = tablaRecompensas.getSelectedRow();
            if (fila == -1) {
                btnCanjear.setEnabled(false);
                return;
            }

            Recompensa r = (Recompensa) modeloTabla.getValueAt(fila, 0);
            btnCanjear.setEnabled(usuarioLogueado.getPuntos() >= r.getCostePuntos());
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanjear;
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JMenuItem espaniol;
    private javax.swing.JMenuItem ingles;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRecompensas;
    // End of variables declaration//GEN-END:variables
    
     /**
     * Aplica los textos traducidos según el idioma actual.
     */
    @Override
    public void aplicarIdioma() {
        setTitle(I18n.t("reward.title"));
        btnCanjear.setText(I18n.t("reward.redeem"));

        tablaRecompensas.getColumnModel().getColumn(1)
                .setHeaderValue(I18n.t("reward.name"));
        tablaRecompensas.getColumnModel().getColumn(2)
                .setHeaderValue(I18n.t("reward.cost"));

        tablaRecompensas.getTableHeader().repaint();
        jMenu1.setText(I18n.t("menu.lenguage"));
        jMenu4.setText(I18n.t("menu.sesion"));

        cerrarSesion.setText(I18n.t("menu.logout"));
        espaniol.setText(I18n.t("menu.spanish"));
        ingles.setText(I18n.t("menu.english"));
        jMenu2.setText(I18n.t("menu.help"));
        jMenuItem5.setText(I18n.t("menu.controls"));
    }
}
