/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yhon.dam.proyectodamnavidad.vista;

import com.yhon.dam.proyectodamnavidad.controller.RecuperarControlador;
import com.yhon.dam.proyectodamnavidad.controller.RecuperarControlador.Resultado;
import com.yhon.dam.proyectodamnavidad.dao.UsuarioDAO;
import com.yhon.dam.proyectodamnavidad.modelo.Usuario;
import com.yhon.dam.proyectodamnavidad.util.EmailUtil;
import com.yhon.dam.proyectodamnavidad.util.I18n;
import com.yhon.dam.proyectodamnavidad.util.I18nAware;
import com.yhon.dam.proyectodamnavidad.util.PasswordGenerator;
import com.yhon.dam.proyectodamnavidad.util.PasswordUtil;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


/**
 * Ventana de recuperación de contraseña.
 * <p>
 * Permite al usuario solicitar la recuperación de su contraseña
 * introduciendo su correo electrónico. El sistema enviará una
 * nueva contraseña si el correo existe.
 * </p>
 *
 * Soporta internacionalización dinámica mediante {@link I18nAware}.
 *
 * @author yhon
 */
public class RecuperarPasswordVista extends javax.swing.JFrame implements I18nAware {
    
    
    /** Logger de la clase */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecuperarPasswordVista.class.getName());

     /**
     * Crea la ventana de recuperación de contraseña.
     */
    public RecuperarPasswordVista() {
        initComponents();
        getRootPane().setDefaultButton(btnRecuperar);
        aplicarIdioma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRecuperar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        espaniol = new javax.swing.JMenuItem();
        ingles = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("email");

        btnRecuperar.setText("Recuperar");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });

        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("RECUPERAR CONTRASEÑA");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recuperarpass.png"))); // NOI18N

        jMenu4.setText("Sesion");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Nuevo Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Idioma");

        espaniol.setText("Español");
        espaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaniolActionPerformed(evt);
            }
        });
        jMenu1.add(espaniol);

        ingles.setText("Ingles");
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        jMenu1.add(ingles);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem5.setText("Controles");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bntCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnRecuperar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Gestiona la solicitud de recuperación de contraseña.
     * <p>
     * Valida el correo introducido y delega la lógica
     * en {@link RecuperarControlador}.
     * </p>
     */
    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        String email = txtEmail.getText().trim();

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    I18n.t("recover.emptyEmail"),
                    I18n.t("common.warning"),
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        RecuperarControlador controller = new RecuperarControlador();
        Resultado r = controller.recuperar(email);

        switch (r) {

            case OK:
            case EMAIL_NO_EXISTE: {

                Object[] options = {I18n.t("common.ok")};

                JOptionPane.showOptionDialog(
                        this,
                        I18n.t("recover.sent"),
                        I18n.t("common.info"),
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null,
                        options,
                        options[0]
                );

                this.dispose();
                break;
            }

            case ERROR: {

                Object[] options = {I18n.t("common.ok")};

                JOptionPane.showOptionDialog(
                        this,
                        I18n.t("recover.error"),
                        I18n.t("common.error"),
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.ERROR_MESSAGE,
                        null,
                        options,
                        options[0]
                );

                break;
            }
        }

    }//GEN-LAST:event_btnRecuperarActionPerformed
    
    /**
     * Abre la ventana de registro de nuevo usuario.
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        RegistroVista registro = new RegistroVista();
        registro.setLocationRelativeTo(this);
        registro.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        RegistroVista registro = new RegistroVista();
        registro.setLocationRelativeTo(this); // centrado respecto al login
        registro.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed
    
    
     /**
     * Cambia el idioma a español.
     */
    private void espaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaniolActionPerformed
        // TODO add your handling code here:
        I18n.setLanguage("es");
        aplicarIdioma();
    }//GEN-LAST:event_espaniolActionPerformed
    
     /**
     * Cambia el idioma a ingles.
     */
    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        // TODO add your handling code here:
        I18n.setLanguage("en");
        aplicarIdioma();
    }//GEN-LAST:event_inglesActionPerformed
    
    /**
     * Muestra la ventana de ayuda.
     */
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Object[] options = {I18n.t("common.ok")};

        JOptionPane.showOptionDialog(
                this,
                I18n.t("help.content"),
                I18n.t("help.title"),
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]
        );
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
     /**
     * Cancela la recuperación y cierra la ventana.
     */
    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RecuperarPasswordVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JMenuItem espaniol;
    private javax.swing.JMenuItem ingles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Aplica los textos traducidos según el idioma actual.
     */
    @Override
    public void aplicarIdioma() {
        setTitle(I18n.t("recover.title"));
        jLabel1.setText(I18n.t("recover.email"));
        btnRecuperar.setText(I18n.t("recover.button"));
        jLabel2.setText(I18n.t("recover.h1"));
        jMenu4.setText(I18n.t("menu.sesion"));
        jMenuItem2.setText(I18n.t("menu.newuser"));
        bntCancelar.setText(I18n.t("common.cancel"));
        espaniol.setText(I18n.t("menu.spanish"));
        ingles.setText(I18n.t("menu.english"));
        jMenu2.setText(I18n.t("menu.help"));
        jMenuItem5.setText(I18n.t("menu.controls"));
        jMenu1.setText(I18n.t("menu.lenguage"));
    }
}
